### ISSUE TITLE
doesn't work with libc++

### ISSUE THREAD

**Issue by gzmask** [konteck/wpp#3]
clang++ -std=c++11 -stdlib=libc++ -o bin/run src/demo.cpp

src/web++.hpp:466:73: error: invalid operands to binary expression ('__bind<int
      &, sockaddr *, unsigned long>' and 'int')
        if (bind(sc, (struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 error generated.

**Comment by gzmask** [comment]
solution is pretty simply but im too lazy to make pull request:
if (::bind(sc, (struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0) {

instead of 

if (bind(sc, (struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0) {

**Comment by gzmask** [comment]
server.all("/dir", "./"); gives a blank page even after the fix. Something is not working with libc++ for sure.

**Comment by alexk7** [comment]
works for me with the modification.

**Comment by detro** [comment]
I wonder if @konteck is stil supporting this project.
I was considering integrating it into PhantomJS, but would be more valuable if actual development was still ongoing...

**Comment by mmaraya** [comment]
@gzmask, could you please see if commit 38c6e9e fixes the problem for you?  Thanks.
