### ISSUE TITLE
list_dir allows directory traversion

### ISSUE THREAD

**Issue by yvesf** [konteck/wpp#5]
example: 
c++: `server.get("/public", "./public");`

url: `http://localhost:5000/public?open=/../../../../../../../../etc/passwd`

expectation: list_dir should only allow access to files below the shared directory

**Comment by mmaraya** [comment]
It looks like an attempt to prevent directory traversal was made in the original version: https://github.com/konteck/wpp/blob/215475a058353faec53c19dfa5331226c21ea9bf/web%2B%2B.hpp#L196-L203.  A couple of tweaks should make it work correctly.
